language: ruby
rvm:
  - 2.1.5
  - 2.2.1
env:
  - RAILS_VER=3.2.19
  - RAILS_VER=4.2.1
services:
  - rabbitmq
before_script:
  - cp test/internal/config/database.yml.travis test/internal/config/database.yml